### ISSUE TITLE
[conflict], first time user may be really confused

### ISSUE THREAD

**Issue by borestad** [slushjs/gulp-conflict#4]
Hi. Cool plugin, really like the effort.

This is me running a sample project for the first time:
I've read the other issues about the Keeping/Creating issue, but for me this is still not as clear as it can be.

This basically screams YOU HAVE A CONFLICT. But i suppose this green [conflict] is from gulp, right? Is behavior possible to modify?

I also have to say that 'Create' or 'Creating' is a better name imho. At least in the context when using it together with slush

![image](https://cloud.githubusercontent.com/assets/286455/4901235/a9500ea6-642f-11e4-894f-464109fbbb87.png)

**Comment by mshick** [comment]
Would be great to see this included, maybe via that PR? I've had to explain the [conflict] thing a few times already -- very confusing.
